# -*- coding: utf-8 -*-
"""Phase2_Skincare_Data (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AU4EoxnjpuST05QXv_gPWtSdELwQO5c

# 🧴 Phase 2 — Data Acquisition & Preprocessing
## Explainable AI-Based Personalized Skincare Recommendation System

**Dataset:** Acne Dataset Image — [tiswan14/acne-dataset-image](https://www.kaggle.com/datasets/tiswan14/acne-dataset-image)

---
| Section | Description |
|---|---|
| 1 | Environment Setup |
| 2 | Data Collection (Kaggle API + Manual Fallback) |
| 3 | Dataset Inspection & Folder Discovery |
| 4 | Exploratory Data Analysis (EDA) |
| 5 | Data Cleaning |
| 6 | Preprocessing (Resize, Normalize, Augment, Split) |
| 7 | Final Summary |

---
## Section 1 — Environment Setup
"""

!pip install kaggle imagehash opencv-python-headless pillow matplotlib seaborn scikit-learn tqdm -q

import os, json, shutil, hashlib, warnings, zipfile, glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import imagehash
from PIL import Image, UnidentifiedImageError
from pathlib import Path
from tqdm import tqdm
from collections import defaultdict
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 120

DATASET_DIR = '/content/acne_dataset'
os.makedirs(DATASET_DIR, exist_ok=True)

print('✅ All libraries loaded.')
print(f'   TensorFlow : {tf.__version__}')
print(f'   Dataset dir: {DATASET_DIR}')

"""---
##  Section 2 — Data Collection

> **Evidence of data gathering:** Dataset downloaded via official Kaggle API.
> Source: https://www.kaggle.com/datasets/tiswan14/acne-dataset-image
"""

from google.colab import files
print('📎 Upload your kaggle.json file...')
print('   Get it: kaggle.com → Profile → Settings → API → Create New Token')
uploaded = files.upload()

os.makedirs('/root/.kaggle', exist_ok=True)
shutil.move('kaggle.json', '/root/.kaggle/kaggle.json')
os.chmod('/root/.kaggle/kaggle.json', 0o600)
print(' Kaggle API key configured.')

KAGGLE_SLUG = 'tiswan14/acne-dataset-image'
print(f' Downloading: {KAGGLE_SLUG}')
print('   Please wait...\n')

exit_code = os.system(f'kaggle datasets download -d {KAGGLE_SLUG} -p {DATASET_DIR} --unzip')

if exit_code != 0:
    print('\n⚠️  Download failed. Use manual upload:')
    print('   1. Go to: https://www.kaggle.com/datasets/tiswan14/acne-dataset-image')
    print('   2. Download the ZIP → upload it here via Colab Files panel')
    print('   3. Run the next cell to extract it')
else:
    print(' Download complete!')

# Manual upload fallback — run this ONLY if the download above failed
zip_files = glob.glob('/content/*.zip')
if zip_files:
    zip_path = zip_files[0]
    print(f'📦 Found ZIP: {zip_path} — extracting...')
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(DATASET_DIR)
    print(f' Extracted to {DATASET_DIR}')
else:
    contents = [f for f in os.listdir(DATASET_DIR) if not f.startswith('.')]
    if contents:
        print(f' Dataset already present ({len(contents)} items) — no action needed.')
    else:
        print(' No ZIP found. Please upload the dataset ZIP manually.')

"""---
##  Section 3 — Dataset Inspection & Folder Discovery
"""

# Print full directory tree
VALID_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.webp', '.tiff'}
print('📂 Directory structure:')
print('=' * 55)
for root, dirs, files_list in os.walk(DATASET_DIR):
    dirs.sort()
    level = root.replace(DATASET_DIR, '').count(os.sep)
    indent = '  ' * level
    img_count = sum(1 for f in files_list if Path(f).suffix.lower() in VALID_EXTENSIONS)
    label = f'  [{img_count} images]' if img_count > 0 else ''
    if level <= 3:
        print(f'{indent} {os.path.basename(root)}/{label}')
print('=' * 55)

# Build master DataFrame with auto label detection
def normalize_label(folder_name):
    name = folder_name.strip().lower().replace('-','_').replace(' ','_')
    mapping = {
        'mild':'Mild','level_0':'Mild','level0':'Mild','0':'Mild','grade_0':'Mild',
        'moderate':'Moderate','level_1':'Moderate','level1':'Moderate','1':'Moderate',
        'severe':'Severe','level_2':'Severe','level2':'Severe','2':'Severe',
        'very_severe':'Very Severe','level_3':'Very Severe','level3':'Very Severe','3':'Very Severe',
        'acne':'Acne','acne_face':'Acne','pimple':'Acne','non_acne':'Normal',
        'normal':'Normal','clear':'Normal','healthy':'Normal','no_acne':'Normal',
        'blackhead':'Blackhead','blackheads':'Blackhead',
        'whitehead':'Whitehead','pustule':'Pustule','cystic':'Cystic',
    }
    return mapping.get(name, folder_name.replace('_',' ').title())

records = []
for root, dirs, files_list in os.walk(DATASET_DIR):
    img_files = [f for f in files_list if Path(f).suffix.lower() in VALID_EXTENSIONS]
    if not img_files: continue
    folder_name = os.path.basename(root)
    label = normalize_label(folder_name)
    for img_file in img_files:
        records.append({
            'filepath': os.path.join(root, img_file),
            'filename': img_file,
            'class_folder': folder_name,
            'label': label,
            'extension': Path(img_file).suffix.lower()
        })

df = pd.DataFrame(records)
assert not df.empty, ' No images found! Check dataset extraction.'
print(f'Total images found : {len(df)}')
print(f'   Classes detected  : {df["label"].nunique()}')
print(f'\nClass distribution:')
print(df['label'].value_counts().to_string())
display(df.head(6))

"""---
##  Section 4 — Exploratory Data Analysis (EDA)
"""

# Colour palette setup
CLASSES = df['label'].value_counts().index.tolist()
N = len(CLASSES)
BASE_PALETTE = ['#4CAF50','#2196F3','#FF9800','#E91E63','#9C27B0','#00BCD4','#FF5722','#607D8B']
COLORS  = BASE_PALETTE[:N]
COLOR_MAP = dict(zip(CLASSES, COLORS))
print(f'Classes  : {CLASSES}')
print(f'Colours  : {COLORS}')

# EDA 1 — Class Distribution
class_counts = df['label'].value_counts()
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle('Figure 1 — Class Distribution  |  Acne Dataset Image', fontsize=14, fontweight='bold')

bars = axes[0].bar(class_counts.index, class_counts.values,
                   color=[COLOR_MAP[c] for c in class_counts.index], edgecolor='white', linewidth=1.2, width=0.55)
for bar, val in zip(bars, class_counts.values):
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+max(class_counts)*0.01,
                 str(val), ha='center', va='bottom', fontweight='bold', fontsize=11)
axes[0].set_ylim(0, class_counts.max()*1.18)
axes[0].set_xlabel('Class'); axes[0].set_ylabel('Number of Images')
axes[0].set_title('Image Count per Class', fontweight='bold')
axes[0].tick_params(axis='x', rotation=20)

wedges, texts, autotexts = axes[1].pie(
    class_counts.values, labels=class_counts.index,
    colors=[COLOR_MAP[c] for c in class_counts.index],
    autopct='%1.1f%%', startangle=140,
    wedgeprops={'edgecolor':'white','linewidth':2}, textprops={'fontsize':10})
for at in autotexts: at.set_fontweight('bold')
axes[1].set_title(f'Class Proportions  (Total: {len(df)} images)', fontweight='bold')

plt.tight_layout()
plt.savefig('/content/fig1_class_distribution.png', bbox_inches='tight', dpi=150, facecolor='white')
plt.show()
print(' Figure 1 saved.')

# EDA 2 — Sample Images
SAMPLES = 4
fig, axes = plt.subplots(N, SAMPLES, figsize=(14, 3.5*N))
if N == 1: axes = [axes]
for row_idx, label in enumerate(CLASSES):
    subset = df[df['label']==label].sample(min(SAMPLES, len(df[df['label']==label])), random_state=42)
    for col_idx in range(SAMPLES):
        ax = axes[row_idx][col_idx] if N > 1 else axes[col_idx]
        if col_idx < len(subset):
            try:
                ax.imshow(Image.open(subset.iloc[col_idx]['filepath']).convert('RGB'))
                ax.set_title(f'Sample {col_idx+1}', fontsize=8, color='gray')
            except:
                ax.text(0.5,0.5,'Error',ha='center',transform=ax.transAxes)
        else:
            ax.axis('off'); continue
        ax.axis('off')
        if col_idx == 0:
            ax.set_ylabel(label, fontsize=11, fontweight='bold',
                          color=COLOR_MAP[label], rotation=0, labelpad=70)
fig.suptitle('Figure 2 — Sample Images per Class', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('/content/fig2_sample_images.png', bbox_inches='tight', dpi=150, facecolor='white')
plt.show()
print(' Figure 2 saved.')

# EDA 3 — Dimension Analysis
print('📐 Analysing image dimensions...')
widths, heights, fsizes = [], [], []
for _, row in tqdm(df.iterrows(), total=len(df), desc='Reading'):
    try:
        with Image.open(row['filepath']) as img:
            w, h = img.size
        widths.append(w); heights.append(h)
        fsizes.append(os.path.getsize(row['filepath'])/1024)
    except:
        widths.append(None); heights.append(None); fsizes.append(None)
df['width']=widths; df['height']=heights
df['aspect_ratio']=df['width']/df['height']; df['file_size_kb']=fsizes
print('\n Statistics:')
display(df[['width','height','aspect_ratio','file_size_kb']].describe().round(2))

# EDA 4 — Dimension Plots
fig, axes = plt.subplots(2, 2, figsize=(13, 9))
fig.suptitle('Figure 3 — Image Dimension & File Size Analysis', fontsize=14, fontweight='bold')
axes[0,0].hist(df['width'].dropna(), bins=40, color='#1976D2', edgecolor='white', alpha=0.9)
axes[0,0].axvline(df['width'].median(), color='red', linestyle='--', linewidth=2, label=f'Median: {int(df["width"].median())}px')
axes[0,0].set_title('Width Distribution'); axes[0,0].set_xlabel('Width (px)'); axes[0,0].set_ylabel('Count'); axes[0,0].legend()
axes[0,1].hist(df['height'].dropna(), bins=40, color='#E64A19', edgecolor='white', alpha=0.9)
axes[0,1].axvline(df['height'].median(), color='blue', linestyle='--', linewidth=2, label=f'Median: {int(df["height"].median())}px')
axes[0,1].set_title('Height Distribution'); axes[0,1].set_xlabel('Height (px)'); axes[0,1].set_ylabel('Count'); axes[0,1].legend()
sc=axes[1,0].scatter(df['width'].dropna(), df['height'].dropna(), c=df['aspect_ratio'].dropna(), cmap='plasma', alpha=0.35, s=15, edgecolors='none')
axes[1,0].axline((0,0),slope=1,color='lime',linestyle='--',linewidth=1.5,label='Square 1:1')
plt.colorbar(sc, ax=axes[1,0], label='Aspect Ratio')
axes[1,0].set_title('Width vs Height'); axes[1,0].set_xlabel('Width (px)'); axes[1,0].set_ylabel('Height (px)'); axes[1,0].legend()
axes[1,1].hist(df['file_size_kb'].dropna(), bins=40, color='#00796B', edgecolor='white', alpha=0.9)
axes[1,1].axvline(df['file_size_kb'].median(), color='orange', linestyle='--', linewidth=2, label=f'Median: {df["file_size_kb"].median():.1f} KB')
axes[1,1].set_title('File Size Distribution'); axes[1,1].set_xlabel('File Size (KB)'); axes[1,1].set_ylabel('Count'); axes[1,1].legend()
plt.tight_layout()
plt.savefig('/content/fig3_dimensions.png', bbox_inches='tight', dpi=150, facecolor='white')
plt.show()
print('Figure 3 saved.')

# EDA 5 — RGB Intensity per Class
print(' Computing RGB intensities...')
class_rgb = defaultdict(lambda: {'R':[],'G':[],'B':[]})
for _, row in tqdm(df.iterrows(), total=len(df), desc='RGB'):
    try:
        arr = np.array(Image.open(row['filepath']).convert('RGB').resize((64,64)), dtype=np.float32)
        class_rgb[row['label']]['R'].append(arr[:,:,0].mean())
        class_rgb[row['label']]['G'].append(arr[:,:,1].mean())
        class_rgb[row['label']]['B'].append(arr[:,:,2].mean())
    except: pass
rgb_rows=[{'Label':lbl,'Mean R':np.mean(v['R']),'Mean G':np.mean(v['G']),'Mean B':np.mean(v['B'])} for lbl,v in class_rgb.items()]
rgb_df=pd.DataFrame(rgb_rows).set_index('Label').reindex(CLASSES)
print('\n RGB per Class:'); display(rgb_df.round(2))
fig,axes=plt.subplots(1,2,figsize=(13,5))
fig.suptitle('Figure 4 — Mean RGB Intensity per Class', fontsize=14, fontweight='bold')
x=np.arange(N); w=0.26
axes[0].bar(x-w,rgb_df['Mean R'],w,label='Red',color='#E53935',alpha=0.88,edgecolor='white')
axes[0].bar(x,  rgb_df['Mean G'],w,label='Green',color='#43A047',alpha=0.88,edgecolor='white')
axes[0].bar(x+w,rgb_df['Mean B'],w,label='Blue',color='#1E88E5',alpha=0.88,edgecolor='white')
axes[0].set_xticks(x); axes[0].set_xticklabels(rgb_df.index,rotation=15)
axes[0].set_ylabel('Mean Pixel Intensity (0-255)'); axes[0].set_title('Mean RGB per Class'); axes[0].legend()
axes[1].plot(CLASSES,rgb_df['Mean R'],'o-',color='#E53935',lw=2,ms=8,label='Red')
axes[1].plot(CLASSES,rgb_df['Mean G'],'s-',color='#43A047',lw=2,ms=8,label='Green')
axes[1].plot(CLASSES,rgb_df['Mean B'],'^-',color='#1E88E5',lw=2,ms=8,label='Blue')
axes[1].set_title('RGB Trend'); axes[1].tick_params(axis='x',rotation=15); axes[1].legend()
plt.tight_layout()
plt.savefig('/content/fig4_rgb_intensity.png', bbox_inches='tight', dpi=150, facecolor='white')
plt.show()
print('Figure 4 saved.')

# EDA 6 — Boxplot per Class
fig,axes=plt.subplots(1,2,figsize=(13,5))
fig.suptitle('Figure 5 — Width & Height Variance per Class', fontsize=14, fontweight='bold')
df_d=df.dropna(subset=['width','height'])
sns.boxplot(data=df_d,x='label',y='width',order=CLASSES,palette=COLOR_MAP,ax=axes[0],linewidth=1.2)
axes[0].set_title('Width per Class'); axes[0].tick_params(axis='x',rotation=20)
sns.boxplot(data=df_d,x='label',y='height',order=CLASSES,palette=COLOR_MAP,ax=axes[1],linewidth=1.2)
axes[1].set_title('Height per Class'); axes[1].tick_params(axis='x',rotation=20)
plt.tight_layout()
plt.savefig('/content/fig5_dimension_boxplot.png', bbox_inches='tight', dpi=150, facecolor='white')
plt.show()
print(' Figure 5 saved.')

"""---
## Section 5 — Data Cleaning
"""

raw_count = len(df)
print(f'Starting dataset size: {raw_count} images\n')

# Step 1: Corrupted images
print(' Step 1: Corrupted images...')
corrupted = []
for idx,row in tqdm(df.iterrows(),total=len(df),desc='Verifying'):
    try:
        with Image.open(row['filepath']) as img: img.verify()
    except: corrupted.append(idx)
print(f'   Found  : {len(corrupted)}')
df.drop(index=corrupted,inplace=True); df.reset_index(drop=True,inplace=True)
print(f'   Remaining: {len(df)}')

# Step 2: Exact duplicates (MD5)
print(' Step 2: Exact duplicates (MD5 hash)...')
df['md5']=[hashlib.md5(open(p,'rb').read()).hexdigest() for p in tqdm(df['filepath'],desc='MD5')]
before=len(df)
df.drop_duplicates(subset='md5',keep='first',inplace=True); df.reset_index(drop=True,inplace=True)
exact_dups_removed=before-len(df)
print(f'   Removed  : {exact_dups_removed}')
print(f'   Remaining: {len(df)}')

# Step 3: Near-duplicates (perceptual hash)
print('Step 3: Near-duplicates (perceptual hash, threshold=5)...')
phashes=[]
for p in tqdm(df['filepath'],desc='pHash'):
    try: phashes.append(imagehash.phash(Image.open(p)))
    except: phashes.append(None)
df['phash']=phashes
THRESHOLD=5
near_dups=set()
plist=df['phash'].tolist()
for i in range(len(plist)):
    if i in near_dups or plist[i] is None: continue
    for j in range(i+1,len(plist)):
        if plist[j] is not None and abs(plist[i]-plist[j])<=THRESHOLD: near_dups.add(j)
print(f'   Found  : {len(near_dups)}')
df.drop(index=list(near_dups),inplace=True); df.reset_index(drop=True,inplace=True)
print(f'   Remaining: {len(df)}')

# Step 4: Dimension outliers
print(' Step 4: Dimension outliers...')
MIN_DIM,MAX_DIM=50,6000
before=len(df)
df=df[df['width'].notna()&df['height'].notna()&(df['width']>=MIN_DIM)&(df['height']>=MIN_DIM)&(df['width']<=MAX_DIM)&(df['height']<=MAX_DIM)].reset_index(drop=True)
print(f'   Removed  : {before-len(df)}')
print(f'   Remaining: {len(df)}')

# Step 5: Missing values
print('\n Step 5: Missing values...')
missing=df.isnull().sum()
mc=missing[missing>0]
print('   None found.' if mc.empty else mc.to_string())
df.dropna(subset=['filepath','label'],inplace=True); df.reset_index(drop=True,inplace=True)
print(f'\n CLEANING COMPLETE — {len(df)} images remain')
print(df['label'].value_counts().to_string())

# Cleaning Pipeline Chart
stages=['Raw\nDataset','After\nCorruption\nRemoval','After\nExact Dup\nRemoval','After\nNear-Dup\nRemoval','Final\nClean Dataset']
stage_counts=[raw_count,raw_count-len(corrupted),raw_count-len(corrupted)-exact_dups_removed,raw_count-len(corrupted)-exact_dups_removed-len(near_dups),len(df)]
stage_colors=['#90A4AE','#FFCA28','#FB8C00','#E53935','#4CAF50']
fig,ax=plt.subplots(figsize=(12,5))
fig.suptitle('Figure 6 — Data Cleaning Pipeline', fontsize=14, fontweight='bold')
bars=ax.bar(stages,stage_counts,color=stage_colors,edgecolor='white',linewidth=1.2,width=0.55)
for bar,val in zip(bars,stage_counts):
    ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()+raw_count*0.004,str(val),ha='center',va='bottom',fontsize=12,fontweight='bold')
ax.set_ylabel('Number of Images'); ax.set_ylim(0,raw_count*1.15)
plt.tight_layout()
plt.savefig('/content/fig6_cleaning_pipeline.png',bbox_inches='tight',dpi=150,facecolor='white')
plt.show()
print(' Figure 6 saved.')

"""---
##  Section 6 — Preprocessing
"""

# Label Encoding
unique_labels=sorted(df['label'].unique())
label_to_int={lbl:idx for idx,lbl in enumerate(unique_labels)}
int_to_label={v:k for k,v in label_to_int.items()}
df['label_encoded']=df['label'].map(label_to_int)
print(' Label Encoding:')
for lbl,code in label_to_int.items(): print(f'   {code}  →  {lbl}')

# Resize + Normalise demo
IMG_SIZE=(224,224)
def preprocess_image(filepath):
    img=Image.open(filepath).convert('RGB')
    resized=img.resize(IMG_SIZE,Image.LANCZOS)
    arr=np.array(resized,dtype=np.float32)/255.0
    return img,resized,arr

orig,res,norm=preprocess_image(df['filepath'].iloc[0])
fig,axes=plt.subplots(1,3,figsize=(13,4))
fig.suptitle('Figure 7 — Preprocessing: Resize & Normalize',fontsize=14,fontweight='bold')
axes[0].imshow(orig); axes[0].set_title(f'Original\n{orig.size[0]}×{orig.size[1]}px',fontweight='bold'); axes[0].axis('off')
axes[1].imshow(norm); axes[1].set_title(f'Resized + Normalized\n224×224px | range [0,1]',fontweight='bold'); axes[1].axis('off')
orig_arr=np.array(orig)
axes[2].hist(orig_arr.ravel(),bins=50,alpha=0.55,color='#E53935',label='Original (0-255)')
ax2=axes[2].twinx()
ax2.hist(norm.ravel(),bins=50,alpha=0.45,color='#1E88E5',label='Normalized (0-1)')
axes[2].set_xlabel('Pixel Value'); axes[2].set_ylabel('Count (Original)'); ax2.set_ylabel('Count (Normalized)')
axes[2].set_title('Pixel Intensity Histogram',fontweight='bold')
lines1,labels1=axes[2].get_legend_handles_labels()
lines2,labels2=ax2.get_legend_handles_labels()
axes[2].legend(lines1+lines2,labels1+labels2,fontsize=8)
plt.tight_layout()
plt.savefig('/content/fig7_preprocessing.png',bbox_inches='tight',dpi=150,facecolor='white')
plt.show()
print(' Figure 7 saved.')

# ── Figure 8 — Data Augmentation (FIXED) ──────────────────────────
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageEnhance
import random

def augment_image(img_array_norm, aug_type):
    """Apply a specific augmentation to a normalized [0,1] float32 image."""
    # Work in uint8 space to avoid range issues
    img = Image.fromarray((img_array_norm * 255).astype(np.uint8))
    W, H = img.size

    if aug_type == 'Rotation':
        img = img.rotate(random.choice([-25, -15, 15, 25]), expand=False, fillcolor=(128,128,128))
    elif aug_type == 'H-Flip':
        img = img.transpose(Image.FLIP_LEFT_RIGHT)
    elif aug_type == 'Zoom':
        crop = 0.82
        left, top = int(W*(1-crop)/2), int(H*(1-crop)/2)
        img = img.crop((left, top, W-left, H-top)).resize((W, H), Image.LANCZOS)
    elif aug_type == 'Brightness':
        img = ImageEnhance.Brightness(img).enhance(random.uniform(0.6, 1.4))
    elif aug_type == 'Shift':
        shift_x = int(W * 0.12)
        shift_y = int(H * 0.12)
        img = img.transform(img.size, Image.AFFINE, (1,0,shift_x,0,1,shift_y), fillcolor=(128,128,128))
    elif aug_type == 'Rot+Flip':
        img = img.rotate(20, fillcolor=(128,128,128)).transpose(Image.FLIP_LEFT_RIGHT)
    elif aug_type == 'Zoom+Bright':
        crop = 0.85
        left, top = int(W*(1-crop)/2), int(H*(1-crop)/2)
        img = img.crop((left, top, W-left, H-top)).resize((W,H), Image.LANCZOS)
        img = ImageEnhance.Brightness(img).enhance(1.3)
    elif aug_type == 'Shift+Rot':
        img = img.transform(img.size, Image.AFFINE, (1,0,int(W*0.1),0,1,int(H*0.1)), fillcolor=(128,128,128))
        img = img.rotate(-20, fillcolor=(128,128,128))
    elif aug_type == 'All Combined':
        img = img.rotate(15, fillcolor=(128,128,128))
        img = img.transpose(Image.FLIP_LEFT_RIGHT)
        img = ImageEnhance.Brightness(img).enhance(1.2)
        crop = 0.88
        left, top = int(W*(1-crop)/2), int(H*(1-crop)/2)
        img = img.crop((left, top, W-left, H-top)).resize((W,H), Image.LANCZOS)

    return np.array(img, dtype=np.float32) / 255.0

# Build the figure
aug_types = ['Rotation','H-Flip','Zoom','Brightness','Shift',
             'Rot+Flip','Zoom+Bright','Shift+Rot','All Combined']

fig, axes = plt.subplots(2, 5, figsize=(16, 7))
fig.suptitle('Figure 8 — Data Augmentation Samples', fontsize=14, fontweight='bold')

# Original
axes[0][0].imshow(np.clip(norm, 0, 1))
axes[0][0].set_title('Original', fontweight='bold', color='green')
axes[0][0].axis('off')

for i, aug_type in enumerate(aug_types):
    r, c = divmod(i + 1, 5)
    result = augment_image(norm, aug_type)
    axes[r][c].imshow(np.clip(result, 0, 1))
    axes[r][c].set_title(aug_type, fontsize=9, color='#1565C0')
    axes[r][c].axis('off')

plt.tight_layout()
plt.savefig('/content/fig8_augmentation.png', bbox_inches='tight', dpi=150, facecolor='white')
plt.show()
print(' Figure 8 saved.')

# Train / Val / Test Split
train_df,temp_df=train_test_split(df,test_size=0.30,stratify=df['label'],random_state=42)
val_df,test_df=train_test_split(temp_df,test_size=0.50,stratify=temp_df['label'],random_state=42)
train_df=train_df.copy(); train_df['split']='train'
val_df=val_df.copy();   val_df['split']='val'
test_df=test_df.copy();  test_df['split']='test'
print(f'Train : {len(train_df)} ({len(train_df)/len(df)*100:.1f}%)')
print(f'Val   : {len(val_df)} ({len(val_df)/len(df)*100:.1f}%)')
print(f'Test  : {len(test_df)} ({len(test_df)/len(df)*100:.1f}%)')
fig,axes=plt.subplots(1,3,figsize=(14,5))
fig.suptitle('Figure 9 — Stratified Train/Val/Test Split',fontsize=14,fontweight='bold')
for ax,(name,sdf),col in zip(axes,[('Training (70%)',train_df),('Validation (15%)',val_df),('Test (15%)',test_df)],['#1565C0','#2E7D32','#C62828']):
    counts=sdf['label'].value_counts().reindex(CLASSES,fill_value=0)
    bars=ax.bar(counts.index,counts.values,color=col,alpha=0.85,edgecolor='white',width=0.55)
    for bar,val in zip(bars,counts.values):
        ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.5,str(val),ha='center',va='bottom',fontsize=10,fontweight='bold')
    ax.set_title(name,fontweight='bold',color=col); ax.set_xlabel('Class'); ax.set_ylabel('Count')
    ax.tick_params(axis='x',rotation=20)
    ax.text(0.97,0.97,f'n={len(sdf)}',transform=ax.transAxes,ha='right',va='top',fontsize=10,color=col,fontweight='bold')
plt.tight_layout()
plt.savefig('/content/fig9_split.png',bbox_inches='tight',dpi=150,facecolor='white')
plt.show()
print(' Figure 9 saved.')

# Save manifest CSV
final_df=pd.concat([train_df,val_df,test_df]).reset_index(drop=True)
cols=['filepath','filename','label','label_encoded','width','height','aspect_ratio','file_size_kb','split']
final_df[cols].to_csv('/content/acne_dataset_manifest.csv',index=False)
print(' Saved: /content/acne_dataset_manifest.csv')
display(final_df[cols].head(6))

"""---
##  Section 7 — Final Summary
"""

print('='*60)
print('  PHASE 2 — DATA ACQUISITION & PREPROCESSING SUMMARY')
print('='*60)
print(f'  Dataset   : kaggle.com/datasets/tiswan14/acne-dataset-image')
print(f'  Total     : {len(final_df)} images')
print(f'  Classes   : {", ".join(CLASSES)}')
print(f'  IMG Size  : {IMG_SIZE[0]}x{IMG_SIZE[1]} px  |  Norm: [0,1]')
print(f'  Encoding  : {label_to_int}')
print('-'*60)
print('  Cleaning:')
print(f'    Corrupted removed    : {len(corrupted)}')
print(f'    Exact dups removed   : {exact_dups_removed}')
print(f'    Near-dups removed    : {len(near_dups)}')
print('-'*60)
print('  Splits:')
print(f'    Train : {len(train_df)} (70%)  |  Val: {len(val_df)} (15%)  |  Test: {len(test_df)} (15%)')
print('-'*60)
print('  Augmentation: Rotation 25°, H-Flip, Zoom 18%,')
print('                Brightness [0.75-1.25], Shift 12%')
print('-'*60)
print('  Figures: fig1 to fig9 saved to /content/*.png')
print('='*60)